---
- hosts: webservers
  become: true
 
  tasks:
    # Install Nginx
    - name: Install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    # Start Nginx
    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

    # Basic homepage
    - name: Create index.html
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <body>
            <h1>Hello from {{ ansible_hostname }}</h1>
            <p>Internal DNS: {{ domain }}</p>
          </body>
          </html>
        dest: /var/www/html/index.html

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted