---
- hosts: webservers
  become: true
  vars:
    domain: "batman.{{ domain_name }}" # From terraform.tfvars
    internal_domain: "nginx.senrep.internal" 

  tasks:
    # Install Nginx
    - name: Install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    # Start Nginx
    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded